### PR TITLE
Update to symfony 7

### PR DESCRIPTION
**Pull request by larowlan**

### CODE REVIEW

**Comment by andypost** [comment]
There's some `ContainerAware`  usage which needs clean-up to fix tests
https://www.drupal.org/project/drupal/issues/3397519

**Comment by mdranove** [comment]
> There's some `ContainerAware` usage which needs clean-up to fix tests https://www.drupal.org/project/drupal/issues/3397519

Added [this PR](https://github.com/Chi-teck/drupal-code-generator/pull/141) to fix.

**Comment by Chi-teck** [comment]
I merged this branch into 4.x. Thank you.

**Comment by larowlan** [comment]
🎉

**Pull request closed without merging**
