### PR TITLE
Allow symfony/filesystem v6

### PR DESCRIPTION
**Pull request by mfb**
I was able to install this package with symfony/filesystem v6, but I also had to allow the dev-master version of friendsoftwig/twigcs as there is not yet a compatible release of that package.

### CODE REVIEW

**Comment by Chi-teck** [comment]
`friendsoftwig/twigcs` is a dev dependency of this project. Do we really have to upgrade it?

**Comment by mfb** [comment]
Pushed a new commit that only allows symfony/filesystem v6 (so tests won't yet be able to run on v6)

**Comment by mfb** [comment]
Not sure what's going on with phpcs being hosed.  Seems to be caused by current versions of chi-teck/drupal-coder-extension, phpstan/phpdoc-parser and slevomat/coding-standard - if I downgrade these, phpcs runs without issue.

**Comment by Chi-teck** [comment]
Seems lik slevomat has dropped some sniffs. I'll check it later.

**Comment by Chi-teck** [comment]
Seems like phpcs is broken by Drupal Coder.
https://www.drupal.org/project/coder/issues/3262291

**Comment by Chi-teck** [comment]
Thank you

**Pull request merged**
