### PR TITLE
Remove deprecated drupal_set_message() function from install.twig template

### PR DESCRIPTION
**Pull request by Niklan**
Replaced deprecated `drupal_set_message()` with Drupal::messenger().

[drupal_get_message() and drupal_set_message() replaced by Messenger service](https://www.drupal.org/node/2774931)

### CODE REVIEW

**Comment by Chi-teck** [comment]
Actually messages don't make much sense here. I propose we replace them with the following.
`// @DCG Place your code here.`

**Comment by Niklan** [comment]
Seems like there are other places needs to be taking into account. E.g. entity generator has alot of `drupal_set_message()` calls.

**Comment by Chi-teck** [comment]
Let's fix the `install` generator for now.

**Comment by Chi-teck** [comment]
> Actually messages don't make much sense here. I propose we replace them with the following.
> `// @DCG Place your code here.`

Eventually I reverted this change because it did not pass PHP Code sniffer validation.
```
FILE: /tmp/dcg_sut/modules/bar/bar.install
----------------------------------------------------------------------
FOUND 2 ERRORS AFFECTING 2 LINES
----------------------------------------------------------------------
 11 | ERROR | Empty installation hooks are not necessary
 18 | ERROR | Empty installation hooks are not necessary
----------------------------------------------------------------------

Time: 332ms; Memory: 12Mb
```

**Pull request merged**
