### PR TITLE
Add support for SDC slots 

### LINKED ISSUE #190: SDC generator should support slots
Bug taken from the drush issue queue : https://github.com/drush-ops/drush/issues/6131

<p dir="auto"><strong>Describe the bug</strong><br>
Running <code class="notranslate">drush generate sdc</code> creates a single directory component.</p>
<p dir="auto">Components may contain <code class="notranslate">props</code> and <code class="notranslate">slots</code>.</p>
<p dir="auto">The generator asks if I want to create <code class="notranslate">props</code>, but not <code class="notranslate">slots</code>.  <code class="notranslate">props</code> are correctly added to the <code class="notranslate">props</code> section of the component.</p>
<p dir="auto">However, the created component has attempts to use a <code class="notranslate">slot</code> called "example_block" without it being defined in the <code class="notranslate">slots</code> section of the component.yml file. This results in a compiler error when attempting to use the default component.</p>
<p dir="auto"><strong>To Reproduce</strong></p>
<p dir="auto">I ran <code class="notranslate">drush generate sdc</code>, selected a theme name and component name, specified no properties, and used defaults for all other options.</p>
<p dir="auto">The generated <code class="notranslate">.twig</code> file contains the following:</p>
<div class="snippet-clipboard-content notranslate position-relative overflow-auto"><pre class="notranslate"><code class="notranslate">  {% block example_block %}
    The contents of the example block
  {% endblock %}
</code></pre><div class="zeroclipboard-container position-absolute right-0 top-0">
    </div></div><p dir="auto">This implements a slot called "example_block". However, as there are no slots defined in the .component.yml file.</p>
<p dir="auto">When attempting to view the generated component, the use of an undefined slot results in a compile error.</p>
<p dir="auto"><strong>Expected behavior</strong><br>
If the default .twig file contains a <code class="notranslate">{% block %}</code>, the block should be defined in the .component.yml.</p>
<p dir="auto">The simple fix would be to add the slots section to the .component.yml file.</p>
<p dir="auto">An even better fix would be to ask about slots after the questions about props, and create a  <code class="notranslate">{% block %}</code> item for each slot, and a matching entry in .component.yml.</p>
<p dir="auto"><strong>Actual behavior</strong><br>
The current default component results in a compile error.</p>
<p dir="auto"><strong>Workaround</strong><br>
It's fairly simple to fix, either by removing the <code class="notranslate">block</code> and <code class="notranslate">endblock</code>, or by adding the <code class="notranslate">slot</code> definition. However, it would be great if new users were given a working component out of the box.</p>
<h3 dir="auto">System Configuration</h3>
<markdown-accessiblity-table data-catalyst="">
Q | A
-- | --
Drush version? | 12.5.2.0
Drupal version? | 10.3
PHP version | 8.2
OS? | Linux

</markdown-accessiblity-table>
<p dir="auto"><strong>Additional information</strong><br>
None.</p>

### PR DESCRIPTION
**Pull request by PierrePaul**
Fixes #190

### CODE REVIEW

**Comment by PierrePaul** [comment]
Tests are failing, but it doesn't seem to be related to SDC. 
It seems to be related to PhpStormMetaTest. For some reasons though, it doesn't seem to be failing on other PR (maybe because they are failing at the lint step though). Closed PR from two weeks ago seems fine though.

**Comment by PierrePaul** [comment]
@Chi-teck for some reasons I can't explain, the PhpStormMetaTest used to work fine and stops working on Drupal 11.x after commit https://git.drupalcode.org/project/drupal/-/commit/b72df4495eb2f51d5b87b8ad7018fd913c9eb096 

The PhpStormMetaTest assertDatabase is looking for the table 'cache_bootstrap' and can't find it. At this point I'm not sure if this is a new bug in D11 or if expected behavior and PhpStormMetaTest should be updated. 

In any case, this should probably be done in a separate issue. If you have some insights (or maybe @weitzman ?), I can take care of this.

**Comment by PierrePaul** [comment]
My bad, I wasn't resetting my git tree correctly before the tests. 
The "bad" commit is actually : https://git.drupalcode.org/project/drupal/-/commit/1584d2c9f2e6718034f5c7c051d702a75a5dae62
Which makes a lot more sense than the other one.

**Comment by Chi-teck** [comment]
@PierrePaul the tests were broken in 4.x branch as well. @chesn0k has just fixed it and updated this feature branch.

**Review by chesn0k — APPROVED** [review]
Thank you

**Pull request merged**
